# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11980a6bd1bec388181e32a9f22dde2d8d8ca8a122c0a8c3b054420ad266a1660374bf3fdb89906cb10feebd0c841414dbacdf05cc31a629ab476e1f37ff5b94

test:
  secret_key_base: 7e878ff8df125500f6871663e2985e5feb816f2e986087a7368eaea27012ee278ff4362059c1d68c68741d983d2424c6d468e2bf1045522bc5f0e98ca84561c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
